version: '3'
services:
  logging-service:
    image: blockchainlg/activity-logging-service
    ports:
      - "3033:3033"
    environment:
      THREADS: 2              
      NETWORK: "ropsten"
      SERVER_PORT: 3033
      ETH_RPC_URL: http://40.71.88.86
      ETH_RPC_PORT: 9919
      ACTIVITY_LOGGER_ADDR: "0xa474f10ab92b3092445b7da15bbe7b60719a7297"
    networks:
      logging-service-net:
        ipv4_address: 172.27.1.3

networks:
  logging-service-net:
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/16
